spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/tdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=root
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=30000
##################################################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#################################################################################
spring.security.private=962c9567a36334772bb8ef67734d8fbb0e53ab00f6a8cadb0990b770fb04363b
spring.security.expiration=86400000
#################################################################################
countries.api.url=https://restcountries.com/v3.1/all?fields=name,country,capital,region,population,currencies,flag